name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t aminetakha/docker-react -f Dockerfile.dev .
      - run: docker run aminetakha/docker-react npm run test -- --coverage
